// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:577919622150:web:e3370ea18c91f488ceb787',
    messagingSenderId: '577919622150',
    projectId: 'dyslexiaapp-1',
    authDomain: 'dyslexiaapp-1.firebaseapp.com',
    storageBucket: 'dyslexiaapp-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:577919622150:android:93d065adce3692fcceb787',
    messagingSenderId: '577919622150',
    projectId: 'dyslexiaapp-1',
    storageBucket: 'dyslexiaapp-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:577919622150:ios:e1dd675cf1cd31b6ceb787',
    messagingSenderId: '577919622150',
    projectId: 'dyslexiaapp-1',
    storageBucket: 'dyslexiaapp-1.firebasestorage.app',
    iosBundleId: 'com.example.lexiplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:577919622150:ios:e1dd675cf1cd31b6ceb787',
    messagingSenderId: '577919622150',
    projectId: 'dyslexiaapp-1',
    storageBucket: 'dyslexiaapp-1.firebasestorage.app',
    iosBundleId: 'com.example.lexiplay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:577919622150:web:3a66680c338ef80dceb787',
    messagingSenderId: '577919622150',
    projectId: 'dyslexiaapp-1',
    authDomain: 'dyslexiaapp-1.firebaseapp.com',
    storageBucket: 'dyslexiaapp-1.firebasestorage.app',
  );
}
